name: DevSecOps Pipeline
on:
  push:
    branches: [ main ]

# This block ensures that the GitHub Action workflow has permissions to write comments and update pull requests:
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
    # Pre-commit hook to scan for secrets/ leaks in the codebase using TruffleHog
    secret-scanning:
        runs-on: ubuntu-latest
        steps:
            # Check out the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0  # setting `fetch-depth` to `0` ensures that no tags or branches are excluded from the scan.

            # Run TruffleHog to scan for secrets/ leaks in the codebase
            - name: Run TruffleHog
              uses: trufflesecurity/trufflehog-action@v1
              with:
                args: --json --entropy=True --rules=rules.json .
              continue-on-error: true # This allows the workflow to continue because we know FOR SURE this gonna fail.

    # GATE#1: SAST scan using SonarQube
    sast-scan:
        runs-on: ubuntu-latest
        needs: secret-scanning # runs after the "secret-scanning" is complete
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Run SonarQube scan
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v4.1.0
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # for more details on how to generate the SONAR_TOKEN, check the link provided above.

    #GATE#2: Dependency scanning using OWASP Dependency-Check
    dependency-scanning:
        runs-on: ubuntu-latest
        needs: [sast-scan, secret-scanning] # this job will run only if the "sast-scan" and "secret-scanning" jobs are successful
        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: build the project
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            # Run OWASP Dependency-Check scan
            - name: Depcheck
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'test'
                path: '.'
                format: 'HTML'
                out: 'reports' # this is the default, no need to specify unless you wish to override it
                args: >
                    --failOnCVSS 7
                    --enableRetired

            # Upload the generated report as an artifact for later use
            - name: Upload Test results
              uses: actions/upload-artifact@master
              with:
                name: Depcheck report
                path: ${{github.workspace}}/reports

    # GATE#3: Container/Image scanning using Trivy
    image-scanning:
        runs-on: ubuntu-latest
        needs: [dependency-scanning] # this job will run only if the "dependency-scanning" job is successful
        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            # Build the Docker image (
            - name: Build Docker image
              run: docker build -t my-app:latest .

            # Run Trivy scan on the built image
            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'my-app:latest'
                format: 'table'
                severity: 'HIGH,CRITICAL'

    # GATE#4: Infrastructure as Code (IaC) scanning using Checkov. Sine this is too much for you (and me), let's skip this part as well haha
    # but you can check out the Checkov GitHub Action here: https://github.com/marketplace/actions/checkov-github-action

    # GATE#5: DAST scan using OWASP ZAP (well, there is a workshop for this, so let's skip this part)
